name: drawer_swipe
description: Drawer swipe Package for displaying multi layer drawer
version: 0.0.2
homepage: https://www.pharous.com/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
