name: drawer_swipe
description: Drawer swipe Package for displaying multi layer drawer
version: 0.0.3
homepage: https://www.pharous.com/
repository: https://github.com/pharous-flutter/drawer_swip
issue_tracker: https://github.com/pharous-flutter/drawer_swip/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
